version: '3.8'

services:
  # Frontend service (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:81/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - chicken-network

  # Backend service (Spring Boot)
  backend:
    build:
      context: ./backend/chicken
      dockerfile: Dockerfile
    ports:
      - "81:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chicken_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    networks:
      - chicken-network

  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: chicken-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chicken_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chicken-network

networks:
  chicken-network:
    driver: bridge

volumes:
  postgres-data: 