version: '3.8'

services:
  # Override frontend for development
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  # Override backend for development
  backend:
    volumes:
      - ./backend/chicken:/app
      - maven-cache:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  # Add pgAdmin for database management in development
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    networks:
      - chicken-network
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
      - ./docker/servers.json:/pgadmin4/servers.json

volumes:
  maven-cache: 